# Site Settings
title: Testing the test testingly 
email: fake@fake.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/"
url: "https://chris642.github.io"
twitter_username: fake
github_username:  fake
# Build Settings
sass:
  sass_dir: _sass
  style: :expanded
include: ['_pages']
kramdown:
  input: GFM
collections:
  projects:
   output: true
   
