# Site Settings
title: Informatyka w Procesach Biznesowych 
email: fake@fake.com
description: >
  Strona poświęcona studiom na kierunku Informatyka w Procesach Biznesowych
baseurl: "/"
url: "https://chris642.github.io"
plugins:
  - jekyll-sitemap

twitter_username: fake
github_username:  fake
# Build Settings
sass:
  sass_dir: _sass
  style: :expanded
include: ['_pages']
kramdown:
  input: GFM
collections:
  projects:
   output: true
   
