# Site Settings
title: Testing the test testingly 
email: fake@fake.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/Testsite"
url: "http://localhost:4000"
twitter_username: fake
github_username:  fake
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  projects:
   output: true
   
